(function(p){var t=window.AmazonUIPageJS||window.P,K=t._namespace||t.attributeErrors,d=K?K("MSXBooksDetailPageAsset"):t;d.guardFatal?d.guardFatal(p)(d,window):d.execute(function(){p(d,window)})})(function(p,t,K){p.when("A","jQuery","atf").execute(function(d,a,b){if(a("#bookDescription_feature_div").length){var c=a("#outer_postBodyPS").height();a("#postBodyPS").height()>c+30?(a("#outer_postBodyPS").show(),a("#outer_postBodyPS").css("height",c),a("#psPlaceHolder").show(),a("#expandPS").show(),a("#collapsePS").hide()):
(a("#outer_postBodyPS").css("height","auto"),a("#psPlaceHolder").hide());a("#bookDescription_feature_div .a-link-expander").click(function(){a("#bdSeeAllPrompt").is(":hidden")?(a("#outer_postBodyPS").animate({height:c},500),a("#bdSeeAllPrompt").show(),a("#bdSeeLessPrompt").hide()):(a("#outer_postBodyPS").animate({height:a("#postBodyPS").height()},500),a("#bdSeeAllPrompt").hide(),a("#bdSeeLessPrompt").show());a("#bdExpanderIcon").toggleClass("rotate");return!1})}});p.when("A","jQuery","DynamicIframe",
"bookDescriptionIframe").execute(function(d,a,b,c){if(a("#bookDescription_feature_div").length){var f=function(){var b=a("#"+p).contentDocument;if(c.staticHeight&&b&&b.defaultView)var d=parseInt(c.numLines,10),e=b.find("#iframeContent"),b=b.defaultView.getComputedStyle(e,null).getPropertyValue("line-height"),b=parseFloat(b),b=Math.round(b*d);else d=document.getElementById(c.featureDiv).offsetTop,b=document.getElementById(c.imageBlockDiv).offsetTop,e=document.getElementById(c.imageBlockDiv).offsetHeight,
b=b+e-d-30,112>b&&(b=112);d=document.getElementById(c.postBodyId).offsetHeight;d>b+30?a("#"+c.seeLessPromptId).hasClass("a-hidden")?(a("#"+c.outerBodyId).height(b),a("#"+c.placeHolderId).removeClass("a-hidden"),a("#"+c.seeAllPromptId).removeClass("a-hidden")):a("#"+c.outerBodyId).height(d):(a("#"+c.outerBodyId).height(d),a("#"+c.placeHolderId).addClass("a-hidden"),a("#"+c.seeAllPromptId).removeClass("a-hidden"),a("#"+c.seeLessPromptId).addClass("a-hidden"),a("#"+c.expanderIconId).removeClass("rotate"));
b=a("#"+c.outerBodyId).height();0==l&&(l=b);b=l;d>b+30&&a("#"+c.seeLessPromptId).is(":hidden")?(a("#"+c.outerBodyId).show(),a("#"+c.outerBodyId).css("height",b),a("#"+c.placeHolderId).show(),a("#expandPS").removeClass("a-hidden"),a("#collapsePS").addClass("a-hidden")):a("#"+c.outerBodyId).css("height","auto")};var e=null;d=c.encodedDescription;var l=0,g={},p=c.iFrameId;g.iframeId=p;g.iframeWrapperId="bookDesc_iframe_wrapper";g.overriddenCSSId="bookDesc_override_CSS";g.encodedIframeContent=
d;g.initialResizeCallback=f;e=new b(g);e.createIframe();"undefined"!==typeof e&&e instanceof b&&(a(t).resize(function(){e.resizeIframe(f)}),a(t).bind("imageResize",function(){e.resizeIframe(f)}));a("#"+c.featureDiv+" .a-link-expander").click(function(){var b="#"+c.outerBodyId,d="#"+c.seeAllPromptId,e="#"+c.seeLessPromptId,f="#"+c.expanderIconId,g="#"+c.postBodyId;a(d).hasClass("a-hidden")?(g=l,a(b).animate({height:g},500),a(d).removeClass("a-hidden"),a(e).addClass("a-hidden"),a(f).removeClass("rotate")):
(a(b).animate({height:a(g).height()},500),a(d).addClass("a-hidden"),a(e).removeClass("a-hidden"),a(f).addClass("rotate"));return!1})}});p.when("A","jQuery","ImageBlockATF","AudibleAudioPlayer","cf").execute(function(d,a,b,c){function f(a){if("undefined"!==typeof a){var b=t.ue;if(b&&b.count){var c=b.count(a)||0;b.count(a,c+1)}}}function e(){var a=t.innerWidth||document.body.offsetWidth;if(!(0>=a))if(a>b.windowWidthThreshold&&C.width()<=b.configWidths[0]){var a=b.configWidths[1],c=a/b.holderRatio,d=
b.frontImageWidth,q=b.frontImageHeight;l(a,c,d,q)}else a<b.windowWidthThreshold&&C.width()>b.configWidths[0]&&(a=b.configWidths[0],c=a/b.holderRatio,b.frontImageAspectRatio>b.holderRatio?(d=a,q=d/b.frontImageAspectRatio):(q=c,d=q*b.frontImageAspectRatio),l(a,c,d,q))}function l(c,d,q,e){if(0<c&&0<d&&0<q&&0<e){Z.css("margin-left",c+b.centerColMargin).removeClass("centerColumn");X.css("width",c);var f=d+b.containerMargin+b.flipLinkMinHeight;C.css("width",c).css("height",f);g(q,e);A.css("height",d-(d-
h.outerHeight())/2);c=(A.outerWidth()-h.outerWidth())/2;d=A.outerHeight()-h.outerHeight();w.css("top",d).css("left",c);m.css("top",d+ca).css("left",c+q-m.width());a(this).trigger("imageResize");u&&u.hide()}}function g(a,b){h.css("width",a).css("height",b);var c=h.width(),e=h.height();w.css("width",c).css("height",e);"undefined"!==typeof n&&0<n.length&&(n.css("width",c).css("height",e),r.css("height",e),q&&W&&(e=r.width(),I=(c-e)/2-2,r.removeClass("ieTransition").css("left",(c-e)/2),"front"==E?r.css("transform",
"perspective(3000px) rotateY(-65deg) translateZ("+I+"px)"):r.css("transform","perspective(3000px) rotateY(90deg) translateZ("+I+"px)"),d.delay(function(){r.addClass("ieTransition")},10)))}function aa(){var a=x.find(".audioSamplePopover");p.when("jQuery","a-popover","ready").execute(function(b,c){u=c.create(Y,{activate:"onclick",position:"triggerRight",inlineContent:a})});N.click(k)}function k(){u&&u.show()}function V(a){a.bind("audioEnded",function(){S.hide();Q.hide();N.show();F=0;u&&u.hide()});a.bind("audioPlaying",
function(){S.hide();N.hide();Q.show();F=1;k()});a.bind("audioPaused",function(){Q.hide();N.hide();S.show();F=0;u&&u.hide()})}function K(){F?z.pause():z.play()}function P(a){if("undefined"!=typeof SitbReader)if("back"==E&&SitbReader.currentBook&&SitbReader.currentBook.bookmarks){a=SitbReader.currentBook.bookmarks.getFirstAndLastPageNumberByName("Back Cover").first;var c=SitbReader.currentBook.bookmarks.getFirstAndLastPageNumberByName("Back Flap").first;a?SitbReader.LightboxActions.openReaderToPage(a):
c?SitbReader.LightboxActions.openReaderToPage(c):SitbReader.LightboxActions.openReader(b.litbData.litbReftag)}else SitbReader.LightboxActions.openReader(b.litbData.litbReftag)}function G(a){W?"click"==a.type?"front"==E?(E="back",h.removeClass("frontUnrotated frontUnrotatedHover").addClass("frontRotated"),n.removeClass("backUnrotated backUnrotatedHover").addClass("backRotated"),r.css("transform","perspective(3000px) rotateY(90deg) translateZ("+I+"px)"),T.addClass("a-hidden"),U.removeClass("a-hidden"),
J.addClass("flipToBackImgRotate"),f("booksImageFlipToBackCount")):(E="front",h.removeClass("frontRotated frontRotatedHover").addClass("frontUnrotated"),n.removeClass("backRotated backRotatedHover").addClass("backUnrotated"),r.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+I+"px)"),U.addClass("a-hidden"),T.removeClass("a-hidden"),J.removeClass("flipToBackImgRotate"),f("booksImageFlipToFrontCount")):"mouseenter"==a.type?"front"==E?(h.removeClass("frontUnrotated").addClass("frontUnrotatedHover"),
n.removeClass("backUnrotated").addClass("backUnrotatedHover"),r.css("transform","perspective(3000px) rotateY(-55deg) translateZ("+I+"px)")):(h.removeClass("frontRotated").addClass("frontRotatedHover"),n.removeClass("backRotated").addClass("backRotatedHover"),r.css("transform","perspective(3000px) rotateY(80deg) translateZ("+I+"px)")):"front"==E?(h.removeClass("frontUnrotatedHover").addClass("frontUnrotated"),n.removeClass("backUnrotatedHover").addClass("backUnrotated"),r.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+
I+"px)")):(h.removeClass("frontRotatedHover").addClass("frontRotated"),n.removeClass("backRotatedHover").addClass("backRotated"),r.css("transform","perspective(3000px) rotateY(90deg) translateZ("+I+"px)")):"click"==a.type?"front"==E?(w.removeClass("bookCanvasTransformHover").addClass("rotated"),T.addClass("a-hidden"),U.removeClass("a-hidden"),J.addClass("flipToBackImgRotate"),E="back",f("booksImageFlipToBackCount")):(w.removeClass("rotated rotatedHover"),U.addClass("a-hidden"),T.removeClass("a-hidden"),
J.removeClass("flipToBackImgRotate"),E="front",f("booksImageFlipToFrontCount")):"mouseenter"==a.type?"front"==E?w.addClass("bookCanvasTransformHover"):w.removeClass("rotated").addClass("rotatedHover"):"front"==E?w.removeClass("bookCanvasTransformHover"):w.removeClass("rotatedHover").addClass("rotated")}function D(){B.addClass("parentImage");r.addClass("bookSpine").removeClass("a-hidden");w.addClass("bookCanvasTransition");h.addClass("bookFrontTransition");d.delay(function(){w.addClass("bookCanvasTransformHover");
d.delay(function(){w.removeClass("bookCanvasTransformHover")},1500)},50)}function M(){var a=r.outerWidth(),b=h.outerWidth();I=(b-a)/2-2;r.css("left",(b-a)/2).css("transform","perspective(3000px) rotateY(-90deg) translateZ("+I+"px)");h.addClass("ieTransition ieBookShadow").css("transform-origin","50% 50% -"+a/2+"px");n.addClass("ieTransition backLanding ieBookShadow").removeClass("a-hidden").css("transform-origin","50% 50% -"+a/2+"px");r.addClass("ieTransition ieBookShadow").removeClass("a-hidden").css("transform-origin",
"50% 50% -"+a/2+"px");d.delay(function(){n.removeClass("backLanding").addClass("backUnrotated");h.addClass("frontUnrotated");r.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+I+"px)")},50);h.mouseenter(function(){r.css("transform","perspective(3000px) rotateY(-75deg) translateZ("+I+"px)")});h.mouseleave(function(){r.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+I+"px)")});H.removeClass("a-hidden")}var C=a("#imageBlock"),B=C.find("#img-wrapper"),A=C.find("#imageBlockContainer"),
w=C.find("#img-canvas"),n=w.find(".backImage"),r=w.find(".sideImage"),h=w.find(".frontImage"),m=a("#imageBlockOuter").find("#sitbLogo"),H=C.find(".flipImageToBack"),x=C.find(".sampleBookAudio"),y=0,E="front",q=0,F=0,N=x.find(".audioListenText"),Q=x.find(".audioPlayingText"),S=x.find(".audioPausedText"),O=x.find(".audioText"),Y=x.find(".audioPopoverTrigger"),z,T=H.find(".flipToBackText"),U=H.find(".flipToFrontText"),J=H.find(".flipToBackImg"),W=a.browser.msie||!!navigator.userAgent.match(/Trident/),
u,X=a("#leftCol"),Z=a("#centerCol"),I=0,ba=a("#imageBlockOuter").find("#sitbLogoImg"),ca=parseInt(C.css("margin-top"));(function(){t.ue&&t.ue.count&&ue.count("booksImageFlipToBackCount",0);t.ue&&t.ue.count&&ue.count("booksImageFlipToFrontCount",0);var f=B.offset(),g=h.offset();if(g){var k=g.top-f.top,f=g.left-f.left,g=h.outerWidth(),u=h.outerHeight(),l=B.outerHeight()-(B.outerHeight()-h.outerHeight())/2,F=r.outerWidth();B.css("position","relative");m.css("top",k+ca).css("left",f+g-m.width());w.css("position",
"absolute").css("top",k).css("left",f).css("width",g).css("height",u);h.css("position","absolute").css("top","0").css("left","0");n.css("position","absolute").css("top","0").css("left","0");r.css("position","absolute").css("top","0").css("left","-"+F+"px");A.css("height",l)}b.audibleData&&b.audibleData.audioSampleSrc&&(z=new c,k={},k.audioSrc=b.audibleData.audioSampleSrc,k.audioId="img-blk-audio-sample",k.audioControllerId=x,k.flashPlayerUrl=b.audibleData.flashPlayerUrl,k.bindEventsCallback=V,z.init(k));
g=1;k=["Perspective","TransformStyle","TransformOrigin","BackfaceVisibility","Transition"];for(f=0;f<k.length;f++)if(g){for(var g=k[f],u=["Webkit","Moz","O","ms"],l=document.createElement("div"),F=!1,p=0;p<u.length;p++)u[p]+g in l.style&&(F=F||!0);"Perspective"===g&&"WebkitPerspective"in l.style&&(F=!1,l.id="test3d",document.body.appendChild(l),3===l.offsetHeight&&(F=!0),l.parentNode.removeChild(l));g=F}y=g;k="undefined"!==typeof n&&0<n.length;(q=y&&k)?(k=h.width(),f=h.height(),0<k&&0<f&&(w.addClass("image-3d"),
n.css("width",k).css("height",f),r.css("height",f),W?M():(D(),n.addClass("bookBack").removeClass("a-hidden"),H.removeClass("a-hidden")),d.declarative("flip-action",["click","mouseenter","mouseleave"],G)),z&&z.isPlayerAvailable?H.addClass("a-span6"):H.addClass("a-span12")):w.addClass("image-2d");b&&b.litbData&&b.litbData.hasLitb&&b.litbData.litbReftag&&(ba.removeClass("a-hidden"),ba.click(P),w.click(P));z&&z.isPlayerAvailable&&(q?x.addClass("a-span6"):x.addClass("a-span12"),Q.hide(),S.hide(),x.removeClass("a-hidden"),
O.children().click(K),k=parseInt,f=N.outerWidth(),g=Q.outerWidth(),u=S.outerWidth(),l=0,0<f&&0<g&&0<u&&(l=Math.max(f,g,u)+5),(k=k(l))&&0<k&&O.css("width",k),aa());b.disableResize||a(t).resize(e)})()});p.when("A","jQuery","ImageBlockATF","ImageGalleryMarkup").execute(function(d,a,b){function c(){var a=b.imageGalleryData;if(a&&0<a.length){m={};H=a.length;for(var c=0;c<a.length;c++)m["ig-thumb-"+c]=a[c]}}function f(){h=D.height();0<M.length&&(h-=M.height());if(a.browser.msie&&7==a.browser.version){var b=
C.outerHeight()-C.height();b&&0<b&&(h-=b)}if(h&&0<h){C.css("height",h);var b=n.height(),c=n.width();B.css("height",b).css("width",c).data("height",b).data("width",c)}}function e(){if(0<D.length){f();g();if(0<H)for(var b=0;b<H;b++){var c="ig-thumb-"+b,c=a('<div class="ig-thumb-image"><img class="ig-thumb-inner '+(c==y?"selected":"")+'" id="'+c+'" src="'+m[c].thumbUrl+'"></div>');w.append(c)}zoomOptions=k();x.setImageData(zoomOptions);x.attachZoomEvents()}}function l(){var a=m[y].dimensions[0],b=m[y].dimensions[1];
A.css("max-width",a).css("max-height",b).removeClass("image-stretch-horizontal image-stretch-vertical");A.addClass(p(a,b))}function g(){m[y]&&(l(),A.attr("src",m[y].mainUrl))}function p(a,b){var c=B.data("width")/B.data("height"),d="image-stretch-vertical";a/b>c&&(d="image-stretch-horizontal");return d}function k(){var a={};m[y]&&(a.containerId="igInner",a.imageId="igImage",a.imageWidth=m[y].dimensions[0],a.imageHeight=m[y].dimensions[1]);return a}function t(){m&&w.find(".ig-thumb-inner").click(function(){var b=
this.id,c=a(this),d=m[b];!c.hasClass("selected")&&d&&(y=b,w.find(".selected").removeClass("selected"),c.addClass("selected"),x.detachEvents(),A.addClass("a-hidden"),r.show(),document.getElementById("igImage").onload=E,g(),b=k(),x.setImageData(b))})}function K(){var a=d.viewport();G.closest(".a-popover-modal").css("width",.75*a.width).css("height",.75*a.height);f();x.detachEvents();l();a=k();x.setImageData(a);x.attachZoomEvents()}function P(){d.capabilities.orientation&&(d.on("orientationchange",function(){K()}),
d.on("a:popover:afterHide:imageGallery",function(){d.off("a:popover:afterHide:imageGallery");d.on("a:popover:beforeShow:imageGallery",function(){K()})}))}var G=a("#imgGalleryContent"),D=G.closest(".a-popover-wrapper"),M=D.find(".a-popover-header"),C=D.find(".a-popover-inner"),B=G.find("#igInner"),A=B.find("#igImage"),w=G.find(".ig-thumbs"),n=G.find(".ig-main-image"),r=G.find(".loading-bar"),h=0,m=null,H=0,x=new function(){function b(){l.bind("touchstart.ig touchmove.ig",function(a){c(a);l.unbind("touchstart.ig touchmove.ig");
l.bind("touchmove.ig",function(a){c(a)});l.bind("touchend.ig",function(a){e.zoomOut();l.unbind("touchstart.ig touchmove.ig touchend.ig");b()})})}function c(a){r&&a.preventDefault();var b,d={},f=h.width(),k=h.height();b=a.pageX-h.offset().left;a=a.pageY-h.offset().top;d.x=n?b*g/f-b:0;d.y=p?a*m/k-a:0;e.zoomIn(d)}var e={},f=null,k=null,g=0,m=0,h=null,l=null,n=!1,p=!1,r=d.capabilities.touch;e.setImageData=function(b){f=b.containerId;k=b.imageId;g=b.imageWidth;m=b.imageHeight;h=a("#"+f);l=a("#"+k);n=0<
g&&0<h.length&&g>h.width();p=0<m&&0<h.length&&m>h.height()};e.attachZoomEvents=function(){if(n||p)h.addClass("zoomable"),r?b():l.click(function(a){h.hasClass("zoomed-in")?(e.zoomOut(),l.unbind("mousemove")):h.hasClass("zoomed-out")&&(c(a),l.mousemove(function(a){c(a)}))})};e.zoomIn=function(a){l.css("top",-1*a.y);l.css("left",-1*a.x);h.removeClass("zoomed-out").addClass("zoomed-in")};e.zoomOut=function(){h.removeClass("zoomed-in").addClass("zoomed-out");l.css("top","auto").css("left","auto")};e.detachEvents=
function(){e.zoomOut();l.unbind();h.removeClass("zoomable")};return e},y;0<G.length&&(y="ig-thumb-0",r.hide(),c(),e(),t(),P());var E=function(){r.hide();A.removeClass("a-hidden");x.attachZoomEvents()}});p.when("A","jQuery").execute(function(d,a){if(a("#imageBlockThumbs").length){var b=function(){var b=a("#imgThumbs"),f=b.data("a-modal"),e=d.viewport();f.width=.75*e.width;f.height=.75*e.height;b.data("a-modal",f)};b();d.on("resize",b)}});p.when("A","jQuery","msxUtility","ready",
"atf").execute(function(d,a,b){function c(c){var e=a("<div></div>").html(c);b.digestPageStates(e);e=null;p.when("responsiveMediaTabsLoadComplete").execute(function(){g.eq(0).html(c);l.find(".olpLink").eq(0).addClass("tabHidden");l.find(".mediaMatrix").eq(0).removeClass("tabHidden");d.trigger("mediaMatrixLazyLoadComplete")});e=a(".otherSellers.mediaMatrix");0<e.length&&e.eq(0).bind("click",f)}function f(c){b.postMetric("mmt-media-matrix-glance-view");a(c.currentTarget).unbind("click",f)}var e=d.state("media-matrix-variables");
if(e){var e="/gp/mediatabs/mediamatrix?"+a.param({asin:e.currentAsin,isMediaMatrixAjaxCall:1,productGroupId:e.productGroupID}),l=a("#mediaTabsHeadings"),g=a("#mediaTab_content_all").find("#MediaMatrix"),t=a("#mediaTab_content_all").find("#MediaMatrixSlot");g&&0<g.length&&t&&0<t.length&&a.ajax({method:"GET",url:e,dataType:"text",success:function(a){a&&/\S/.test(a)?c(a):b.postMetric("mmt-media-matrix-ajax-call-fail")},error:function(a){b.postMetric("mmt-media-matrix-ajax-call-fail")}})}});
p.when("A","jQuery").register("msxUtility",function(d,a){return{digestPageStates:function(a){a.find("script[type='a-state']").each(function(a,b){var e,l,g=b.dataset;g&&g.aState&&(e=JSON.parse(g.aState).key,l=JSON.parse(b.innerText));e&&l&&d.state(e,l)})},postMetric:function(a){if("undefined"!==typeof a){var c=t.ue;if(c){var d=c.count(a)||0;c.count(a,d+1)}}}}})});
/* ******** */
(function(n){var m=window.AmazonUIPageJS||window.P,q=m._namespace||m.attributeErrors,h=q?q("OffersBooksDetailPageAsset"):m;h.guardFatal?h.guardFatal(n)(h,window):h.execute(function(){n(h,window)})})(function(n,m,q){n.when("A","jQuery","atf").execute(function(h,c,d){var k=c("#rbbContainer");k.find(".rbbHeaderLink").attr("href","javascript:void(0);");k.find(".rbbHeader .displayNone i.prime").hide();k.find(".rbbHeader .displayNone .primeBadge").hide();k.find(".rbbHeader .ubbPrimeBadge").hide();k.find(".rbbHeader .prime-plus-price").hide();
k.find(".rbbHeader .displayNone").removeClass("displayNone");c("#rbbContainer .rbbSection.unselected .dp-accordion-inner").hide();var b=c("#buyDealSection").length;c("#rbbContainer .rbbSection .rbbHeader").click(function(a){c(a.target);a=c(this);a=a.hasClass("rbbHeader")?a:a.parents(".rbbHeader");if(a.parents(".rbbSection").hasClass("selected"))return!1;k.find(".selected .a-icon-radio-active").removeClass("a-icon-radio-active").addClass("a-icon-radio-inactive");k.find(".selected .offer-price").removeClass("a-color-price a-size-medium").addClass("a-color-base a-size-base");
k.find("i.a-icon.prime").hide();k.find(".primeBadge").hide();k.find(".ubbPrimeBadge").hide();var d=k.find(".prime-plus-price-grid");d.hasClass("hidden")?d.removeClass("hidden").show():d.addClass("hidden").hide();k.find(".prime-plus-price").show();a.parents(".rbbSection").removeClass("unselected").addClass("selected");a.parents(".rbbSection").toggleClass("dp-accordion-active",500);a.find(".a-icon-radio-inactive").removeClass("a-icon-radio-inactive").addClass("a-icon-radio-active");a.find(".offer-price").removeClass("a-color-base a-size-base").addClass("a-color-price a-size-medium");
a.find("#priceBadgeValue").removeClass("a-size-medium").addClass("a-size-base");a.find("i.a-icon.prime").show();a.find(".primeBadge").show();a.find(".prime-plus-price").hide();c("#rbbContainer .rbbSection .rbbContent").find(".offer-price").removeClass("a-color-base").addClass("a-color-price");a.find(".ubbPrimeBadge").show();var f=c(this).attr("id"),g,h;k.find(".rbbSection").each(function(a,b){c(b).find(".rbbHeader")[0].id==f?g=c(b):c(b).hasClass("selected")&&(h=c(b))});h.find(".rbbContent").slideUp(500,
function(){h.removeClass("selected").addClass("unselected");h.toggleClass("dp-accordion-active",500)});g.find(".rbbContent").slideDown(500);c.browser.msie&&7==parseInt(c.browser.version,10)&&(g.find(".rbbContent").css("display","inline"),setTimeout(function(){g.find(".rbbContent").css("display","block")},505));if(b&&"undefined"!=typeof UDPDealView)if(c("#gbld_header_message").show(),"buyDealSection"==f)UDPDealView.prototype.onSelectLDBuybox();else UDPDealView.prototype.onSelectRegularBuybox();return!0})});
n.when("A","jQuery").execute(function(h,c){c("#one-click-button-ubb, #usedbuyBox #add-to-cart-button-ubb").click(function(){var d=c("#addToCart"),h=d.attr("action").replace("ref=dp_start-bbf_1_glance","ref=dp_start-ubbf_1_glance");d.attr("action",h);return!0});n.when("a-popover").execute(function(d){var k=c("#usedItemConditionInfoLink"),b=d.create(k,{width:250,position:"triggerBottom",activate:h.capabilities.touch?"onmousemove":"onclick",closeButton:!1,popoverLabel:"Used condition details",name:"usedItemConditionDetailsPopover",
dataStrategy:"preload"});k.mouseleave(function(){b.hide()})})})});
/* ******** */
(function(n){var m=window.AmazonUIPageJS||window.P,q=m._namespace||m.attributeErrors,h=q?q("PInfoBooksDetailPageAsset"):m;h.guardFatal?h.guardFatal(n)(h,window):h.execute(function(){n(h,window)})})(function(n,m,q){n.when("A","jQuery","atf").execute(function(h,c,d){var k,b=0;n.when("DPClientLogger").execute(function(){"undefined"!=typeof m.DPClientLogger&&(k=new m.DPClientLogger.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))});c("#bookDetails_feature_div .hero-more").click(function(a){a.preventDefault();
a=c(this).attr("data-popupID");var d=c("#"+a),f=c(this).offset().left+c(this).width()/2,g=c("#popupContent").offset().left,f=(f-g)/c("#popupContent").width()*100;c("#"+a+" .pointer").css({left:f+"%"});c("#popupContent .details-popup").filter(":visible").length?c("#popupContent .details-popup").filter(":visible").attr("id")!==a?(c("#popupContent .details-popup").filter(":visible").slideToggle(300),d.slideToggle(300)):d.slideUp(300):(d.slideDown(300),c(this).hasClass("hero-more")&&c("html,body").animate({scrollTop:c("#bookDetails_feature_div").offset().top-
50},600));k&&!b&&(k.logImpression("ma-books-br-details"),b=1)});c("#bookDetails_feature_div .moreNarratorLink").click(function(){if(location.pathname.replace(/^\//,"")==this.pathname.replace(/^\//,"")||location.hostname==this.hostname){var a=c(this.hash),a=a.length?a:c("[name="+this.hash.slice(1)+"]");a.length&&c("html,body").animate({scrollTop:a.offset().top},1E3);return!1}});c("#bookDetails_feature_div .details-popup button").click(function(a){c(this).parent().slideUp(300)})});n.when("A","jQuery",
"atf").execute(function(h,c,d){function k(){var b=parseInt(c("#byline").width()),a=0;c("#byline .author").each(function(){c(this).is(".notFaded")&&(a+=c(this).outerWidth())});a+=c("#byline .more").outerWidth();if(a>b){var d=c("#byline .author.notFaded").length;c(c("#byline .author.notFaded").get().reverse()).each(function(f){a>b&&f<d-1&&(f=c(this).width(),c(this).removeClass("notFaded"),c(this).fadeOut(10,function(){c(this).hide()}),a-=f,c("#byline .moreCount").html(c("#byline .author").length-c("#byline .author.notFaded").length),
c("#byline .more").addClass("notFaded").fadeIn(10))})}else if(a<b&&c("#byline .author.notFaded").length<c("#byline .author").length){var f=b-a;c("#byline .author").each(function(){if(!c(this).hasClass("notFaded")){var a=c(this).outerWidth();a<=f?(f-=a,c(this).addClass("notFaded").fadeIn(10),a=c("#byline .author").length-c("#byline .author.notFaded").length,0===a?c("#byline .more").removeClass("notFaded").fadeOut(10):(c("#byline .moreCount").html(a),c("#byline .more").addClass("notFaded").fadeIn(10))):
f=0}})}}c("#byline .showMoreLink").click(function(){c("#byline .author").each(function(){c(this).hasClass("notFaded")||c(this).addClass("notFaded").fadeIn(0);c("#byline .more").removeClass("notFaded").fadeOut(0)});return!1});c("#byline .contributorNameID").mouseenter(function(){var b=c(this).attr("data-asin"),a={},d="isAjaxComplete_"+b,f="isAjaxInProgress_"+b,g=h.state("popoverImage-state");a.entityID=b;"1"!==g[d]&&"1"!==g[f]&&(c.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",
data:a,dataType:"html",timeout:1E3,success:function(a){c("#contributorImageContainer"+b).get(0).innerHTML=a;g[d]="1";h.state("popoverImage-state",g)},error:function(){g[f]="0";h.state("popoverImage-state",g)}}),g[f]="1",h.state("popoverImage-state",g))});(function(b){var a=parseInt(b.width()),d=parseInt(b.find(".more").outerWidth()),f=0;c("#byline .author").each(function(){c(this).is(".notFaded")&&(f+=c(this).outerWidth())});c("#byline .more").attr("data-width",d);var g=a-d;if(g>f)b.find(".author").each(function(){var a=
c(this).index();3<=parseInt(a)?(a=c(this).outerWidth(),c(this).attr("data-width",a),a<g?(g-=a,c(this).addClass("notFaded"),c(this).fadeIn("slow")):(g=0,c(this).fadeOut("slow"))):(a=c(this).outerWidth(),c(this).attr("data-width",a),g-=a)});else{var h=c("#byline .author.notFaded").length;c(c("#byline .author.notFaded").get().reverse()).each(function(a){g<f&&a<h-1&&(a=c(this).outerWidth(),f-=a,c(this).fadeOut("slow").removeClass("notFaded"))})}a=b.find(".author").length-b.find(".author.notFaded").length;
0<a&&(b.find(".moreCount").html(a),b.find(".more").fadeIn("slow"),b.find(".more").addClass("notFaded"))})(h.$("#byline"));c(m).resize(function(){k()})});n.when("A","jQuery","atf").execute(function(h,c,d){function k(){var b=parseInt(c("#bylineInfo").width()),a=0;c("#bylineInfo .author").each(function(){c(this).is(".notFaded")&&(a+=c(this).outerWidth())});a+=c("#bylineInfo .more").outerWidth();if(a>b){var d=c("#bylineInfo .author.notFaded").length;c(c("#bylineInfo .author.notFaded").get().reverse()).each(function(f){a>
b&&f<d-1&&(f=c(this).width(),c(this).removeClass("notFaded"),c(this).fadeOut(10,function(){c(this).hide()}),a-=f,c("#bylineInfo .moreCount").html(c("#bylineInfo .author").length-c("#bylineInfo .author.notFaded").length),c("#bylineInfo .more").addClass("notFaded").fadeIn(10))})}else if(a<b&&c("#bylineInfo .author.notFaded").length<c("#bylineInfo .author").length){var f=b-a;c("#bylineInfo .author").each(function(){if(!c(this).hasClass("notFaded")){var a=c(this).outerWidth();a<=f?(f-=a,c(this).addClass("notFaded").fadeIn(10),
a=c("#bylineInfo .author").length-c("#bylineInfo .author.notFaded").length,0===a?c("#bylineInfo .more").removeClass("notFaded").fadeOut(10):(c("#bylineInfo .moreCount").html(a),c("#bylineInfo .more").addClass("notFaded").fadeIn(10))):f=0}})}}c("#bylineInfo .showMoreLink").click(function(){c("#bylineInfo .author").each(function(){c(this).hasClass("notFaded")||c(this).addClass("notFaded").fadeIn(0);c("#bylineInfo .more").removeClass("notFaded").fadeOut(0)});return!1});c("#bylineInfo .contributorNameID").mouseenter(function(){var b=
c(this).attr("data-asin"),a={},d="isAjaxComplete_"+b,f="isAjaxInProgress_"+b,g=h.state("popoverImage-state");a.entityID=b;"1"!==g[d]&&"1"!==g[f]&&(c.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:a,dataType:"html",timeout:1E3,success:function(a){c("#contributorImageContainer"+b).get(0).innerHTML=a;g[d]="1";h.state("popoverImage-state",g)},error:function(){g[f]="0";h.state("popoverImage-state",g)}}),g[f]="1",h.state("popoverImage-state",g))});(function(b){var a=
parseInt(b.width()),d=parseInt(b.find(".more").outerWidth()),f=0;c("#bylineInfo .author").each(function(){c(this).is(".notFaded")&&(f+=c(this).outerWidth())});c("#bylineInfo .more").attr("data-width",d);var g=a-d;if(g>f)b.find(".author").each(function(){var a=c(this).index();3<=parseInt(a)?(a=c(this).outerWidth(),c(this).attr("data-width",a),a<g?(g-=a,c(this).addClass("notFaded"),c(this).fadeIn("slow")):(g=0,c(this).fadeOut("slow"))):(a=c(this).outerWidth(),c(this).attr("data-width",a),g-=a)});else{var h=
c("#bylineInfo .author.notFaded").length;c(c("#bylineInfo .author.notFaded").get().reverse()).each(function(a){g<f&&a<h-1&&(a=c(this).outerWidth(),f-=a,c(this).fadeOut("slow").removeClass("notFaded"))})}a=b.find(".author").length-b.find(".author.notFaded").length;0<a&&(b.find(".moreCount").html(a),b.find(".more").fadeIn("slow"),b.find(".more").addClass("notFaded"))})(h.$("#bylineInfo"));c(m).resize(function(){k()})});n.when("A","jQuery","DynamicIframe","ProductDescriptionData","cf").execute(function(h,
c,d,k){function b(){q=0;var a=Math.min(n,m.length);e(0,a)}function a(){0<H.length&&0<P.length&&(y="collapsed",H.removeClass("a-hidden"),H.click(function(){"collapsed"===y?(r?P.animate({height:"show"}):(P.removeClass("extraReviews"),e(q,m.length),r=1),H.removeClass("collapsed").addClass("expanded"),y="expanded"):(P.animate({height:"hide"}),H.removeClass("expanded").addClass("collapsed"),y="collapsed")}))}function e(a,b){var e;for(e=a;e<b;e++){var g={};g.iframeId="er_iframe_"+e;g.iframeWrapperId="er_iframe_wrapper_"+
e;g.iframeContainerId="er_container_"+e;g.iframeExpanderId="er_expander_"+e;g.iframeColumnId="er_column_"+e;var h=g,k=m[e],n="<h3 class='erSource'>"+k.source+"</h3><div class='erContent'>"+k.content+"</div>";k.footnote&&(n=n+"<em class='erFootnote'>"+k.footnote+"</em>");h.encodedIframeContent=n;g.initialResizeCallback=f;h=g;k={};k.id=c("#"+h.iframeId);k.column=c("#"+h.iframeColumnId);k.wrapper=c("#"+h.iframeWrapperId);k.container=c("#"+h.iframeContainerId);k.expander=c("#"+h.iframeExpanderId);k.iframeObj=
new d(h);k.state="full";h=k;z[g.iframeId]=h;h.column.removeClass("extraReviews");h&&"undefined"!=typeof h.iframeObj&&"function"==typeof h.iframeObj.createIframe&&h.iframeObj.createIframe();l(h);q++}}function f(a){(a=z[a])&&170<a.wrapper.outerHeight()&&(a.container.css("height",140),a.expander.removeClass("a-hidden expanded").addClass("collapsed"),a.state="partial")}function g(a){(a=z[a])&&"full"===a.state&&a.container.css("height",a.wrapper.outerHeight())}function l(a){if(a&&"undefined"!=typeof a.iframeObj&&
"function"==typeof a.iframeObj.resizeIframe)h.on("resize",function(){a.iframeObj.resizeIframe(g)});a&&a.expander&&a.expander.click(function(){"partial"===a.state?(a.container.animate({height:a.wrapper.outerHeight()}),a.expander.removeClass("collapsed").addClass("expanded"),a.state="full"):(a.container.animate({height:140}),a.expander.removeClass("expanded").addClass("collapsed"),c("html, body").animate({scrollTop:a.container.offset().top-20}),a.state="partial")})}var m=k.encodedReviews,n=parseInt(k.reviewsPerRow),
q=0,r=0;k=c("#productDescription-multiColumn");var z={},H,P,y;0<k.length&&m&&0<m.length&&n&&(H=k.find(".reviewsExpander"),P=k.find(".seeMoreProductReviews"),b(),a())})});
/* ******** */
(function(n){var m=window.AmazonUIPageJS||window.P,q=m._namespace||m.attributeErrors,h=q?q("TwisterBooksDetailPageAsset"):m;h.guardFatal?h.guardFatal(n)(h,window):h.execute(function(){n(h,window)})})(function(n,m,q){n.when("A","jQuery","atf").execute(function(h,c){h.on.ready(function(){function d(a,b,d,e,f){c(a).slideToggle(300);c(b).slideToggle(300);c(d).toggleClass("tmmShowPrompt tmmHidePrompt");c(e).toggleClass("tmmShowPrompt tmmHidePrompt");c(f).toggleClass("rotate")}function k(a){a.position();
a.width();c(".swatchElement");a.find(".swatchElement").each(function(){c(this).attr("data-width",c(this).width());z+=c(this).width()});c("#formats").find(".a-row").removeClass("nonJSFormats")}function b(){var b=c("#formats"),d=b.width()-40,f=0,g=0;b.find(".swatchElement").each(function(){c(this).is(":visible")?f+=c(this).width():g++});var h=c(b.find(".swatchElement").get().length),k=b.find(".swatchElement .audibleTitle").length,l=0<h.length&&4<=h[0];(P||y)&&l&&k&&(l=a(f,d),f-=l,P?r.count("mediaMatrixUIOptimization",
1):r.count("mediaMatrixUIOptimizationResizeAndSpillOver",1));f>d?c(b.find(".swatchElement:visible").get().reverse()).each(function(){var a=0,b=!1;c(this).find(".format").hasClass("a-button-selected")?(a=c(this).prev(".swatchElement").width(),b=c(this).prev(".swatchElement").is(":hidden"),c(this).prev(".swatchElement").hide()):(a=c(this).width(),b=c(this).is(":hidden"),c(this).hide());g++;b||(f-=a);return f>d}):f<d&&b.find(".swatchElement").each(function(){if(c(this).is(":hidden")){var a=c(this).width();
a<=d-f&&(c(this).show(),f+=a,g--)}});0==g&&e(f,d,h,z);(y||x)&&k&&(c("#tmmSwatches").css({display:"inline-block","white-space":"normal"}),x&&r.count("mediaMatrixtwisterSpillOver",1),c(b.find(".swatchElement").get().reverse()).each(function(){c(this).is(":hidden")&&c(this).show();c(this).addClass("marginTop")}));!H&&k&&(c.post("/hz/audible/wl",{audible_weblabs:"ADBL_TWISTER_RESIZE_116490"}),H=1);p||(h=c("#audibleTwisterWeblabs"),null!=h&&h.length&&null!=h.data("weblabs")&&(h=h.data("weblabs"),b=b.find(".swatchElement:visible .audibleTitle").length,
h.length&&b&&c.post("/hz/audible/wl",{audible_weblabs:h},function(a){p=!0})))}function a(a,b){var d=c("#formats"),e=0;c(d.find(".swatchElement").get().reverse()).each(function(){var d=f(c(this)),h=c(this).width(),h=h>d?h-d:0;if(a>b&&0<h||c(this).is(":hidden"))g(c(this),d),e+=h,a-=h});return e}function e(a,b,d,e){var h=Math.round(0<d.length?(b-a)/d[0]:0)-10,h=0<h?h:0;0<h&&c("#formats").find(".swatchElement").each(function(){var a=parseInt(c(this).attr("data-width")),d=f(c(this))+(0<h?h:0),a=e<b?a+
1:Math.min(d,a);g(c(this),a)});return h}function f(a){var b=a.find("#kuBadge").length;a=a.find(".a-icon-kindle-unlimited").length;return 0<b||0<a?150:117}function g(a,b){a.addClass("resizedSwatchElement");a.css({width:b+"px"})}var l=0,q=0,p=!1,u,r=m.ue,z=0,H=0,P=c("#twisterResizeWeblab")?c("#twisterResizeWeblab").data("weblabs"):null,y=c("#twisterResizeAndSpillOver")?c("#twisterResizeAndSpillOver").data("weblabs"):null,x=c("#twisterSpillOver")?c("#twisterSpillOver").data("weblabs"):null,A=function(a){"undefined"!=
typeof a&&(u=new a.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))};"undefined"!=typeof amznJQ?amznJQ.available("DPClientLogger",function(){A(m.DPClientLogger)}):n.when("DPClientLogger").execute(A);h.declarative("tmm-see-more-editions-click",["click"],function(a){var b=a.data,e=b.metabindingUrl;if(a.$target.hasClass("a-link-expander")||a.$target.parent().hasClass("a-link-expander")){var b=b.metabindingPlaceHolder,f="#metabinding_row_top_"+b,g="#metabinding_row_bottom_"+b,k="#editionsSeePrompt_"+
b,l="#editionsHidePrompt_"+b,n="#editionsIcon_"+b,p="isAjaxComplete_"+b,q="isAjaxInProgress_"+b;a="#tmmSpinnerDiv_"+b;var r=h.state("mediamatrix-state"),b=r["url_"+b].replace(/&amp;/g,"&");c("#formats .tmmErrorClass").hide();"1"===r[p]||"1"===r[q]?d(f,g,k,l,n):(h.ajax(b,{method:"get",success:function(){r[p]="1";h.state("mediamatrix-state",r);d(f,g,k,l,n)},indicator:c(a),error:function(){c($tmmErrorDiv).show();r[q]="0";h.state("mediamatrix-state",r)}}),r[q]="1",h.state("mediamatrix-state",r))}else"#"!==
e&&(m.location=e)});0<c("#formats > .a-link-expander").length&&r&&r.count&&r.count("mediaMatrixExpanderPresent",1);c("#formats > .a-link-expander").click(function(){d("#tmmSwatches","#twister","#showMoreFormatsPrompt","#hideMoreFormatsPrompt","#formatsIcon");q||(r&&r.count&&r.count("mediaMatrixExpanderClicked",1),q=1);u&&c("#twister").is(":visible")&&!l&&(u.logImpression("tmm-show-more-formats-viewed"),l=1)});c("#formats.responsive").each(function(){k(c(this))});var v=h.state("mediamatrixState"),
C="false";"undefined"!==typeof v&&"undefined"!==typeof v.swatchWrap&&(C=v.swatchWrap);"true"!=C&&(b(),h.on("resize",b));c("#formats .unselected .format").mouseenter(function(){c(this).find(".a-color-secondary").addClass("a-color-price").removeClass("a-color-secondary")}).mouseleave(function(){c(this).find(".a-color-price").addClass("a-color-secondary").removeClass("a-color-price")});c("#landingItemRentalLink").attr("href","javascript:document.getElementById('rentBuySection').click();")})})});
/* ******** */
(function(e){var d=window.AmazonUIPageJS||window.P,f=d._namespace||d.attributeErrors,b=f?f("DetailPageBookProductDescriptionAssets"):d;b.guardFatal?b.guardFatal(e)(b,window):b.execute(function(){e(b,window)})})(function(e,d,f){});
/* ******** */
